// Downloads the two families to public/fonts/ and writes src/styles/fonts.css.
// Self-hosted because the app must work offline and must make zero third-party
// requests at runtime (brief §13). Only the `latin` subset is kept: the UI is
// English, and Zen Kaku Gothic New's Japanese subsets are two orders of
// magnitude larger than our whole font budget.
import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { css: 'Work+Sans:wght@400;500', family: 'Work Sans', slug: 'work-sans' },
  { css: 'Zen+Kaku+Gothic+New:wght@700', family: 'Zen Kaku Gothic New', slug: 'zen-kaku' },
];

const root = new URL('..', import.meta.url);
const outDir = new URL('src/styles/fonts/', root);
await mkdir(fileURLToPath(outDir), { recursive: true });

const faces = [];
const byDigest = new Map();
let total = 0;

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Google emits one @font-face per subset, each preceded by a /* subset */ comment.
  const blocks = css.split('/*').slice(1);
  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    if (subset !== 'latin') continue;
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
    const src = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!weight || !src || !range) continue;

    const bytes = new Uint8Array(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    const digest = createHash('sha1').update(bytes).digest('hex');

    // Google serves one variable file per family and lists it once per requested
    // weight, so the same bytes arrive two or three times. Ship it once and give
    // the @font-face a weight *range* instead.
    const seen = byDigest.get(digest);
    if (seen) {
      seen.weights.push(Number(weight));
      console.log(`${seen.name.padEnd(22)} reused for weight ${weight}`);
      continue;
    }
    const name = `${fam.slug}.woff2`;
    await writeFile(new URL(name, outDir), bytes);
    total += bytes.length;
    const face = { family: fam.family, weights: [Number(weight)], name, range };
    byDigest.set(digest, face);
    faces.push(face);
    console.log(`${name.padEnd(22)} ${(bytes.length / 1024).toFixed(1)} KB`);
  }
}

const css = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted, latin subset only. No third-party request is made at runtime. */
${faces.map((f) => {
  const w = f.weights.length > 1
    ? `${Math.min(...f.weights)} ${Math.max(...f.weights)}`
    : String(f.weights[0]);
  return `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${w};
  font-display: swap;
  src: url('./fonts/${f.name}') format('woff2');
  unicode-range: ${f.range};
}`;
}).join('\n')}
`;
await writeFile(new URL('src/styles/fonts.css', root), css);
console.log(`\ntotal ${(total / 1024).toFixed(1)} KB across ${faces.length} faces (budget 180 KB)`);
