// Generates the one texture in this app: a felt grain tile, authored once to a
// data URI so it costs no request and can never be animated. Run: npm run gen:felt
import { writeFileSync } from 'node:fs';

// fractalNoise at a high base frequency reads as woven nap rather than cloud.
// Four octaves gives the weave a coarse and a fine pass, like real baize.
// stitchTiles keeps the 120px tile seamless when repeated across the board.
const svg = [
  '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120">',
  '<filter id="g" x="0" y="0" width="100%" height="100%">',
  '<feTurbulence type="fractalNoise" baseFrequency="0.86" numOctaves="4" seed="17" stitchTiles="stitch"/>',
  '<feColorMatrix type="saturate" values="0"/>',
  '</filter>',
  '<rect width="120" height="120" filter="url(#g)"/>',
  '</svg>',
].join('');

const encoded = svg
  .replace(/%/g, '%25').replace(/#/g, '%23').replace(/</g, '%3C')
  .replace(/>/g, '%3E').replace(/"/g, "'").replace(/\s{2,}/g, ' ');

writeFileSync(
  new URL('../src/styles/felt.generated.css', import.meta.url),
  `/* GENERATED by scripts/gen-felt.mjs — do not edit by hand.\n`
  + `   The only texture in the app. Board felt only, capped at --grain-alpha. */\n`
  + `:root {\n  --felt-grain: url("data:image/svg+xml,${encoded}");\n  --felt-grain-tile: 120px;\n}\n`,
);
console.log(`felt grain written, ${encoded.length} chars`);
